---
controller_templates:
  - name: F5 Setup
    job_type: run
    inventory: AAP Managed Inventory
    organization: "{{ my_organization }}"
    execution_environment: ansible-automation-platform-25/ee-supported-rhel8
    project: aap.dailydemo.F5
    playbook: playbooks/setup_demo.yml
    credentials:
      - "{{ my_aap_credential }}"
      - Vault - {{ aap_username }}
    extra_vars:
      my_organization: "{{ my_organization }}"
      my_vault: "{{ my_vault }}"
      my_rh_aap_credential: "{{ my_aap_credential }}"
      my_aws_credential: AWS Blank Open Environment pvwk8
      aap_configuration_async_retries: 60

  - name: Panos Setup
    job_type: run
    inventory: AAP Managed Inventory
    organization: "{{ my_organization }}"
    execution_environment: ansible-automation-platform-24/ee-supported-rhel8
    project: aap.dailydemo.Panos
    playbook: playbooks/setup_demo.yml
    credentials:
      - "{{ my_aap_credential }}"
      - Vault - {{ aap_username }}
    extra_vars:
      my_organization: "{{ my_organization }}"
      my_vault: "{{ my_vault }}"
      my_rh_aap_credential: "{{ my_aap_credential }}"
      my_aws_credential: AWS Blank Open Environment pvwk8
      aap_configuration_async_retries: 60

  - name: Setup windows demo
    job_type: run
    inventory: AAP Managed Inventory
    organization: "{{ my_organization }}"
    execution_environment: Default execution environment
    project: aap.dailydemo.windows
    playbook: playbooks/setup_demo.yml
    credentials:
      - "{{ my_aap_credential }}"
      - Vault - {{ aap_username }}
    extra_vars:
      my_organization: "{{ my_organization }}"
      my_vault: "{{ my_vault }}"
      my_rh_aap_credential: "{{ my_aap_credential }}"
      my_aws_credential: AWS Blank Open Environment pvwk8
      aap_configuration_async_retries: 60
  - name: Personal - Plex Server Updated
    job_type: run
    inventory: Plex Server
    organization: "{{ my_organization }}"
    execution_environment: Default execution environment
    project: A's Playbooks
    playbook: plex/upgradeplexserver.yml
    credentials:
      - Plex Server

    extra_vars:
      my_organization: "{{ my_organization }}"
      my_rh_aap_credential: "{{ my_aap_credential }}"
      aap_configuration_async_retries: 60